/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package croco;

import custom.PanelWarnaTransparan;
import custom.background;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.Koneksi;
import view.FormBarangMasuk;
import view.FormBrand;
import view.FormDataBarang;
import view.FormDataMerk;
import view.FormDetailTransaksi;
import view.FormKategoriBarang;
import view.FormLogin;
import view.FormPetugas;
import view.FormCetakLaporan;
import view.FormTransaksi;
import view.LaunchProgressBar;
import view.RiwayatBrgMasuk;

/**
 *
 * @author novalkrnfds
 */
public class FormUtama extends javax.swing.JFrame {
    private Dimension dimension;
    public static FormPetugas formPetugas;
    public static FormLogin formLogin;
    public static FormBarangMasuk formBarangMasuk;
    public static String namaUser,hakAkses;
    static Koneksi koneksi = new Koneksi();
    static Connection con;
    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        setUkuranLokasiFrame(0.85, true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTanggal();
        setJam();
        setIp();
        tampilKonek();
    }
    
    public void fullScreen(){
        dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, dimension.width, dimension.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWarnaTransparan1 = new custom.PanelWarnaTransparan();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new PanelWarnaTransparan();
        mdiDesktopPane = new background();
        txtuser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        logoutMenuItem = new javax.swing.JMenuItem();
        keluarMenuItem = new javax.swing.JMenuItem();
        masterDataMenu = new javax.swing.JMenu();
        dataBarangMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        merkMenuItem = new javax.swing.JMenuItem();
        kategoriMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        supplierMenuItem = new javax.swing.JMenuItem();
        petugasMenuItem = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        brgMasukMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        transaksiMenuItem = new javax.swing.JMenuItem();
        riwayatMenu = new javax.swing.JMenu();
        riwayatMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        detailTransaksiMenuItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        cetakMenuItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        notepadMenuItem = new javax.swing.JMenuItem();
        calcMenuItem = new javax.swing.JMenuItem();

        panelWarnaTransparan1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("P.O.S");

        jLabel5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sofware Point of Sales \"CAST\"");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart-add-icon.png"))); // NOI18N

        javax.swing.GroupLayout panelWarnaTransparan1Layout = new javax.swing.GroupLayout(panelWarnaTransparan1);
        panelWarnaTransparan1.setLayout(panelWarnaTransparan1Layout);
        panelWarnaTransparan1Layout.setHorizontalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelWarnaTransparan1Layout.setVerticalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Croco And Skate Theory Software");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        mdiDesktopPane.setBackground(new java.awt.Color(80, 175, 175));

        javax.swing.GroupLayout mdiDesktopPaneLayout = new javax.swing.GroupLayout(mdiDesktopPane);
        mdiDesktopPane.setLayout(mdiDesktopPaneLayout);
        mdiDesktopPaneLayout.setHorizontalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        mdiDesktopPaneLayout.setVerticalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        txtuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userlogin.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel1");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel1");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder()));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        labelUser.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 624, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtuser)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mdiDesktopPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        fileMenu.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_1.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);
        fileMenu.add(jSeparator3);

        logoutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users_back.png"))); // NOI18N
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuItem);

        keluarMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete2.png"))); // NOI18N
        keluarMenuItem.setText("Exit");
        keluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(keluarMenuItem);

        jMenuBar1.add(fileMenu);

        masterDataMenu.setText("Master Data");

        dataBarangMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/box.png"))); // NOI18N
        dataBarangMenuItem.setText("Data Barang");
        dataBarangMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBarangMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(dataBarangMenuItem);
        masterDataMenu.add(jSeparator1);

        merkMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books.png"))); // NOI18N
        merkMenuItem.setText("Data Merk");
        merkMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(merkMenuItem);

        kategoriMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cube_green.png"))); // NOI18N
        kategoriMenuItem.setText("Kategori Barang");
        kategoriMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(kategoriMenuItem);
        masterDataMenu.add(jSeparator2);

        supplierMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chart_02.png"))); // NOI18N
        supplierMenuItem.setText("Data Brand");
        supplierMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(supplierMenuItem);

        petugasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dude5.png"))); // NOI18N
        petugasMenuItem.setText("Data Petugas");
        petugasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(petugasMenuItem);

        jMenuBar1.add(masterDataMenu);

        transaksiMenu.setText("Transaksi");

        brgMasukMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/package.png"))); // NOI18N
        brgMasukMenuItem.setText("Barang Masuk");
        brgMasukMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brgMasukMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(brgMasukMenuItem);
        transaksiMenu.add(jSeparator5);

        transaksiMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shoppingcart.png"))); // NOI18N
        transaksiMenuItem.setText(" Penjualan");
        transaksiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(transaksiMenuItem);

        jMenuBar1.add(transaksiMenu);

        riwayatMenu.setText("Riwayat");

        riwayatMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/data_table.png"))); // NOI18N
        riwayatMenuItem.setText("Barang Masuk");
        riwayatMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatMenuItemActionPerformed(evt);
            }
        });
        riwayatMenu.add(riwayatMenuItem);
        riwayatMenu.add(jSeparator4);

        detailTransaksiMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paperclip.png"))); // NOI18N
        detailTransaksiMenuItem.setText("Penjualan");
        detailTransaksiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailTransaksiMenuItemActionPerformed(evt);
            }
        });
        riwayatMenu.add(detailTransaksiMenuItem);

        jMenuBar1.add(riwayatMenu);

        laporanMenu.setText("Laporan");

        cetakMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/note.png"))); // NOI18N
        cetakMenuItem.setText("Penjualan");
        cetakMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(cetakMenuItem);

        jMenuBar1.add(laporanMenu);

        toolsMenu.setText("Tools");

        notepadMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveas1.png"))); // NOI18N
        notepadMenuItem.setText("Notepad");
        notepadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notepadMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(notepadMenuItem);

        calcMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        calcMenuItem.setText("Calculator");
        calcMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(calcMenuItem);

        jMenuBar1.add(toolsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ImageIcon iconOk = new ImageIcon(getClass().getResource("/images/server_ok.png"));
    ImageIcon iconError = new ImageIcon(getClass().getResource("/images/server_error.png"));
    
    public void tampilKonek(){
        if((con = koneksi.getKoneksi()) != null){
            setTitle("Croco And Skate Theory Software (Connected)");
            jLabel7.setText("Connected to Database");
            jLabel7.setIcon(iconOk);
        } else {
            setTitle("Croco And Skate Theory Software (Disconnected)");
            jLabel7.setText("Database Disconnected");
            jLabel7.setIcon(iconError);
        }
    }
    
    private void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                String nol_jam = "", nol_menit="",nol_detik="";
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();
                
                if(nilai_jam <= 9) nol_jam = "0";
                if(nilai_menit <= 9) nol_menit = "0";
                if(nilai_detik <= 9) nol_detik = "0";
                
                String waktu = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                
                jLabel4.setText(waktu+" : "+menit+" : "+detik+"");;
            }
        };
        new Timer(1000, taskPerformer).start();
    }
   
   
    private void setTanggal(){
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kalender = new java.text.SimpleDateFormat("dd MMMM yyyy");
        jLabel3.setText(kalender.format(sekarang));
    }
    
    public void setIp(){
        InetAddress host = null;
        try{
            host = InetAddress.getLocalHost();
            byte[] ip = host.getAddress();
            jLabel1.setText("IP : "+ host.getHostAddress());
        } catch (UnknownHostException e){
            jLabel1.setText("IP : 0.0.0.0");
        }
    }
    
    private void setUkuranLokasiFrame(double skala, boolean tengah){
        Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int) (skala * dimensi.getWidth()), (int) (skala * dimensi.getHeight()));
        
        if(tengah) {
            setLocation((int) ((dimensi.getWidth()-getWidth())/2),
                    (int) ((dimensi.getHeight()-getHeight())/2));
        }
    }
    
    public void tampilUser(){
        labelUser.setText(FormUtama.namaUser);
    }
    
    public void admin(){
        transaksiMenu.setEnabled(false);
        masterDataMenu.setEnabled(false);
    }
    
    public void owner(){
        transaksiMenu.setEnabled(false);
    }
    
    public void karyawan(){
        
    }
    
    private void keluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuItemActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "Anda yakin akan keluar ?","", JOptionPane.OK_CANCEL_OPTION);
        if(exit == JOptionPane.OK_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_keluarMenuItemActionPerformed

    private void dataBarangMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBarangMenuItemActionPerformed
        // TODO add your handling code here:
        /*FormDataBarang formBarang = new FormDataBarang();
        formBarang.setBounds((int) (mdiDesktopPane.getWidth()-830)/2, (int) (mdiDesktopPane.getHeight()-550)/2, 830, 550);
        mdiDesktopPane.add(formBarang);
        formBarang.setVisible(true);*/
        
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        FormDataBarang formBarang = new FormDataBarang();
        formBarang.setBounds((int) (mdiDesktopPane.getWidth()-828)/2, (int) (mdiDesktopPane.getHeight()-550)/2, 828, 550);
        mdiDesktopPane.add(formBarang);
        formBarang.setVisible(true);
    }//GEN-LAST:event_dataBarangMenuItemActionPerformed

    private void kategoriMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriMenuItemActionPerformed
        // TODO add your handling code here:
        
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        FormKategoriBarang kategori = new FormKategoriBarang();
        kategori.setBounds((int) (mdiDesktopPane.getWidth()-828)/2, (int) (mdiDesktopPane.getHeight()-557)/2, 828,557);
        mdiDesktopPane.add(kategori);
        kategori.setVisible(true);
    }//GEN-LAST:event_kategoriMenuItemActionPerformed

    private void merkMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkMenuItemActionPerformed
        // TODO add your handling code here:
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        FormDataMerk merk = new FormDataMerk();
        merk.setBounds((int) (mdiDesktopPane.getWidth()-828)/2, (int) (mdiDesktopPane.getHeight()-547)/2,828,547);
        mdiDesktopPane.add(merk);
        merk.setVisible(true);
    }//GEN-LAST:event_merkMenuItemActionPerformed

    private void petugasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasMenuItemActionPerformed
        // TODO add your handling code here:
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        
        FormPetugas petugas = new FormPetugas();
        petugas.setBounds((int) (mdiDesktopPane.getWidth()-828)/2, (int) (mdiDesktopPane.getHeight()-546)/2,828,546);
        mdiDesktopPane.add(petugas);
        petugas.setVisible(true);
        //petugasController.tampilkanDataPetugas();
    }//GEN-LAST:event_petugasMenuItemActionPerformed

    private void transaksiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiMenuItemActionPerformed
        // TODO add your handling code here:
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        
        FormTransaksi transaksi = new FormTransaksi(this, true);
        //transaksi.setBounds(0,0, mdiDesktopPane.getWidth(), mdiDesktopPane.getHeight());
        transaksi.setVisible(true);
    }//GEN-LAST:event_transaksiMenuItemActionPerformed

    private void supplierMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierMenuItemActionPerformed
        // TODO add your handling code here:
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        
        FormBrand b = new FormBrand();
        b.setBounds((int) (mdiDesktopPane.getWidth()-819)/2, (int) (mdiDesktopPane.getHeight()-541)/2, 819,541);
        mdiDesktopPane.add(b);
        b.setVisible(true);
    }//GEN-LAST:event_supplierMenuItemActionPerformed

    private void detailTransaksiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailTransaksiMenuItemActionPerformed
        // TODO add your handling code here:
        FormDetailTransaksi detail = new FormDetailTransaksi();
        detail.setBounds((int) (mdiDesktopPane.getWidth()-830)/2, (int) (mdiDesktopPane.getHeight()-550)/2, 830,550);
        mdiDesktopPane.add(detail);
        detail.setVisible(true);
    }//GEN-LAST:event_detailTransaksiMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void cetakMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakMenuItemActionPerformed
        // TODO add your handling code here:
        FormCetakLaporan cetak = new FormCetakLaporan();
        //cetak.setBounds((int) (mdiDesktopPane.getWidth()-830)/2, (int) (mdiDesktopPane.getHeight()-550)/2, 830,550);
        mdiDesktopPane.add(cetak);
        cetak.setVisible(true);
    }//GEN-LAST:event_cetakMenuItemActionPerformed

    private void brgMasukMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brgMasukMenuItemActionPerformed
        // TODO add your handling code here:
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        
        FormBarangMasuk masuk = new FormBarangMasuk();
        masuk.setBounds((int) (mdiDesktopPane.getWidth()-1004)/2, (int) (mdiDesktopPane.getHeight()-574)/2, 1004,574);
        mdiDesktopPane.add(masuk);
        masuk.setVisible(true);
    }//GEN-LAST:event_brgMasukMenuItemActionPerformed

    private void riwayatMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatMenuItemActionPerformed
        // TODO add your handling code here:
        mdiDesktopPane.removeAll();
        mdiDesktopPane.repaint();
        RiwayatBrgMasuk detail = new RiwayatBrgMasuk();
        detail.setBounds((int) (mdiDesktopPane.getWidth()-821)/2, (int) (mdiDesktopPane.getHeight()-546)/2, 821,546);
        mdiDesktopPane.add(detail);
        detail.setVisible(true);
    }//GEN-LAST:event_riwayatMenuItemActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        //tampilKonek();
    }//GEN-LAST:event_formFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "Anda yakin akan keluar ?","", JOptionPane.OK_CANCEL_OPTION);
        if(exit == JOptionPane.OK_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void notepadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notepadMenuItemActionPerformed
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("notepad");
        } catch (IOException ex) {}
    }//GEN-LAST:event_notepadMenuItemActionPerformed

    private void calcMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcMenuItemActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("calc");
        }catch(IOException ex){}
    }//GEN-LAST:event_calcMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        About about = new About(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormUtama().setVisible(true);
                if ((con = koneksi.getKoneksi()) != null){
                    new FormLogin().setVisible(true);
                    //new FormUtama().setVisible(true);
                    //tampilKonek();
                } else{
                    JOptionPane.showMessageDialog(null, "Koneksi Gagal\n"+koneksi.getPesan());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem brgMasukMenuItem;
    private javax.swing.JMenuItem calcMenuItem;
    private javax.swing.JMenuItem cetakMenuItem;
    private javax.swing.JMenuItem dataBarangMenuItem;
    private javax.swing.JMenuItem detailTransaksiMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem kategoriMenuItem;
    private javax.swing.JMenuItem keluarMenuItem;
    public static javax.swing.JLabel labelUser;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenu masterDataMenu;
    private javax.swing.JDesktopPane mdiDesktopPane;
    private javax.swing.JMenuItem merkMenuItem;
    private javax.swing.JMenuItem notepadMenuItem;
    private custom.PanelWarnaTransparan panelWarnaTransparan1;
    private javax.swing.JMenuItem petugasMenuItem;
    private javax.swing.JMenu riwayatMenu;
    private javax.swing.JMenuItem riwayatMenuItem;
    private javax.swing.JMenuItem supplierMenuItem;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JMenu transaksiMenu;
    private javax.swing.JMenuItem transaksiMenuItem;
    public static javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables
}
